In [21]:
import pandas as pd
df = pd.read_csv('./ME_obsdata16-23.csv')
df

,datetime,Air_Temperature_celsius,Shortwave_Radiation_Downwelling_wattPerMeterSquared,Longwave_Radiation_Downwelling_wattPerMeterSquared,Relative_Humidity_percent,Ten_Meter_Elevation_Wind_Speed_meterPerSecond,Precipitation_millimeterPerDay,Surface_Level_Barometric_Pressure_pascal,secchi_m,tp_ugL,Water_Temp_filled,DO_filled,poc
0,2016-03-21 16:00:00,6.305704,288.034637,294.350815,56.064209,4.653928,0.0,98584.575111,1.947541,80.891319,4.547073,15.137805,1.620866
1,2016-03-21 17:00:00,5.867259,156.870400,294.350815,58.924310,4.362544,0.0,98390.744741,1.945355,80.892003,4.350333,14.826833,1.774744
2,2016-03-21 18:00:00,5.427259,10.915081,257.913481,61.916292,4.431482,0.0,98197.275111,1.943169,80.892686,4.325333,14.702667,1.774319
3,2016-03-21 19:00:00,4.674370,0.000000,257.913481,64.905713,4.486388,0.0,98251.135111,1.940984,80.893370,4.301333,14.545000,1.787338
4,2016-03-21 20:00:00,3.920593,0.000000,257.913481,68.063289,4.554508,0.0,98304.875704,1.938798,80.894053,4.287500,14.458000,1.804376
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66731,2018-11-04 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.552083,123.128906,10.264483,7.760000,0.220400
66732,2019-11-03 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.103623,163.251812,9.681184,11.025098,0.146861
66733,2020-11-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.362179,95.046474,9.677101,9.402609,0.466719
66734,2021-11-07 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.413411,97.845987,11.590104,7.750000,0.335149
66735,2022-11-06 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.404924,88.591180,11.933750,8.746000,0.427875

In [22]:
df.isna().sum()

datetime                                               0
Air_Temperature_celsius                                7
Shortwave_Radiation_Downwelling_wattPerMeterSquared    7
Longwave_Radiation_Downwelling_wattPerMeterSquared     7
Relative_Humidity_percent                              7
Ten_Meter_Elevation_Wind_Speed_meterPerSecond          7
Precipitation_millimeterPerDay                         7
Surface_Level_Barometric_Pressure_pascal               7
secchi_m                                               0
tp_ugL                                                 0
Water_Temp_filled                                      0
DO_filled                                              0
poc                                                    4
dtype: int64

In [23]:
df[df.isna().any(axis=1)]

,datetime,Air_Temperature_celsius,Shortwave_Radiation_Downwelling_wattPerMeterSquared,Longwave_Radiation_Downwelling_wattPerMeterSquared,Relative_Humidity_percent,Ten_Meter_Elevation_Wind_Speed_meterPerSecond,Precipitation_millimeterPerDay,Surface_Level_Barometric_Pressure_pascal,secchi_m,tp_ugL,Water_Temp_filled,DO_filled,poc
49399,2021-11-09 04:00:00,5.685037,0.000000,271.845333,91.216377,3.193177,0.0,98714.048296,3.499740,97.348156,11.571667,10.549255,NaN
49400,2021-11-09 05:00:00,5.168963,0.000000,271.845333,91.661278,3.165023,0.0,98824.641185,3.501432,97.338395,11.563167,10.551313,NaN
49401,2021-11-09 06:00:00,4.648148,0.000000,275.351556,92.054833,3.151267,0.0,98934.930667,3.503125,97.328633,11.544333,10.555875,NaN
49402,2021-11-09 07:00:00,6.011852,27.348622,275.351556,84.415122,3.316179,0.0,98980.553630,3.504818,97.318872,11.539333,10.557087,NaN
66729,2016-11-06 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.366319,44.831597,14.011667,9.986587,0.270308
66730,2017-11-05 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.502229,104.598848,11.023621,7.074483,0.690933
66731,2018-11-04 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.552083,123.128906,10.264483,7.760000,0.220400
66732,2019-11-03 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.103623,163.251812,9.681184,11.025098,0.146861
66733,2020-11-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.362179,95.046474,9.677101,9.402609,0.466719
66734,2021-11-07 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.413411,97.845987,11.590104,7.750000,0.335149
66735,2022-11-06 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.404924,88.591180,11.933750,8.746000,0.427875

In [24]:
df = df[:66729]
df

,datetime,Air_Temperature_celsius,Shortwave_Radiation_Downwelling_wattPerMeterSquared,Longwave_Radiation_Downwelling_wattPerMeterSquared,Relative_Humidity_percent,Ten_Meter_Elevation_Wind_Speed_meterPerSecond,Precipitation_millimeterPerDay,Surface_Level_Barometric_Pressure_pascal,secchi_m,tp_ugL,Water_Temp_filled,DO_filled,poc
0,2016-03-21 16:00:00,6.305704,288.034637,294.350815,56.064209,4.653928,0.0,98584.575111,1.947541,80.891319,4.547073,15.137805,1.620866
1,2016-03-21 17:00:00,5.867259,156.870400,294.350815,58.924310,4.362544,0.0,98390.744741,1.945355,80.892003,4.350333,14.826833,1.774744
2,2016-03-21 18:00:00,5.427259,10.915081,257.913481,61.916292,4.431482,0.0,98197.275111,1.943169,80.892686,4.325333,14.702667,1.774319
3,2016-03-21 19:00:00,4.674370,0.000000,257.913481,64.905713,4.486388,0.0,98251.135111,1.940984,80.893370,4.301333,14.545000,1.787338
4,2016-03-21 20:00:00,3.920593,0.000000,257.913481,68.063289,4.554508,0.0,98304.875704,1.938798,80.894053,4.287500,14.458000,1.804376
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66724,2023-11-01 03:00:00,-7.676264,0.000000,195.132429,93.818286,3.193631,0.0,99196.994268,1.562227,52.910853,11.416333,8.996833,0.397366
66725,2023-11-01 04:00:00,-7.790289,0.000000,195.132429,93.461794,2.871117,0.0,99283.012898,1.562210,52.933140,11.368000,9.044833,0.400298
66726,2023-11-01 05:00:00,-7.906144,0.000000,195.132429,93.103095,2.790575,0.0,99369.029817,1.562194,52.955426,11.330167,9.060833,0.398575
66727,2023-11-01 06:00:00,-8.022722,0.000000,204.770476,92.733901,2.973071,0.0,99455.086908,1.562178,52.977713,11.305517,8.823000,0.399094
66728,2023-11-01 07:00:00,-6.505919,44.679497,204.770476,92.650709,2.650775,0.0,99523.977348,1.562162,53.000000,11.297333,8.644000,0.415732

In [25]:
df = df.fillna(0.5)
df

,datetime,Air_Temperature_celsius,Shortwave_Radiation_Downwelling_wattPerMeterSquared,Longwave_Radiation_Downwelling_wattPerMeterSquared,Relative_Humidity_percent,Ten_Meter_Elevation_Wind_Speed_meterPerSecond,Precipitation_millimeterPerDay,Surface_Level_Barometric_Pressure_pascal,secchi_m,tp_ugL,Water_Temp_filled,DO_filled,poc
0,2016-03-21 16:00:00,6.305704,288.034637,294.350815,56.064209,4.653928,0.0,98584.575111,1.947541,80.891319,4.547073,15.137805,1.620866
1,2016-03-21 17:00:00,5.867259,156.870400,294.350815,58.924310,4.362544,0.0,98390.744741,1.945355,80.892003,4.350333,14.826833,1.774744
2,2016-03-21 18:00:00,5.427259,10.915081,257.913481,61.916292,4.431482,0.0,98197.275111,1.943169,80.892686,4.325333,14.702667,1.774319
3,2016-03-21 19:00:00,4.674370,0.000000,257.913481,64.905713,4.486388,0.0,98251.135111,1.940984,80.893370,4.301333,14.545000,1.787338
4,2016-03-21 20:00:00,3.920593,0.000000,257.913481,68.063289,4.554508,0.0,98304.875704,1.938798,80.894053,4.287500,14.458000,1.804376
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66724,2023-11-01 03:00:00,-7.676264,0.000000,195.132429,93.818286,3.193631,0.0,99196.994268,1.562227,52.910853,11.416333,8.996833,0.397366
66725,2023-11-01 04:00:00,-7.790289,0.000000,195.132429,93.461794,2.871117,0.0,99283.012898,1.562210,52.933140,11.368000,9.044833,0.400298
66726,2023-11-01 05:00:00,-7.906144,0.000000,195.132429,93.103095,2.790575,0.0,99369.029817,1.562194,52.955426,11.330167,9.060833,0.398575
66727,2023-11-01 06:00:00,-8.022722,0.000000,204.770476,92.733901,2.973071,0.0,99455.086908,1.562178,52.977713,11.305517,8.823000,0.399094
66728,2023-11-01 07:00:00,-6.505919,44.679497,204.770476,92.650709,2.650775,0.0,99523.977348,1.562162,53.000000,11.297333,8.644000,0.415732

In [26]:
df.shape

(66729, 13)

In [27]:
df = df[:3000]
df

,datetime,Air_Temperature_celsius,Shortwave_Radiation_Downwelling_wattPerMeterSquared,Longwave_Radiation_Downwelling_wattPerMeterSquared,Relative_Humidity_percent,Ten_Meter_Elevation_Wind_Speed_meterPerSecond,Precipitation_millimeterPerDay,Surface_Level_Barometric_Pressure_pascal,secchi_m,tp_ugL,Water_Temp_filled,DO_filled,poc
0,2016-03-21 16:00:00,6.305704,288.034637,294.350815,56.064209,4.653928,0.000000,98584.575111,1.947541,80.891319,4.547073,15.137805,1.620866
1,2016-03-21 17:00:00,5.867259,156.870400,294.350815,58.924310,4.362544,0.000000,98390.744741,1.945355,80.892003,4.350333,14.826833,1.774744
2,2016-03-21 18:00:00,5.427259,10.915081,257.913481,61.916292,4.431482,0.000000,98197.275111,1.943169,80.892686,4.325333,14.702667,1.774319
3,2016-03-21 19:00:00,4.674370,0.000000,257.913481,64.905713,4.486388,0.000000,98251.135111,1.940984,80.893370,4.301333,14.545000,1.787338
4,2016-03-21 20:00:00,3.920593,0.000000,257.913481,68.063289,4.554508,0.000000,98304.875704,1.938798,80.894053,4.287500,14.458000,1.804376
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2016-07-24 11:00:00,31.957630,810.614363,435.817556,74.619630,5.749848,0.000000,97828.095778,1.883333,20.898810,25.606833,8.507333,0.679156
2996,2016-07-24 12:00:00,33.124222,843.289259,449.250963,71.137623,5.759164,0.000000,97850.734815,1.879167,20.891369,25.747583,8.550667,0.716781
2997,2016-07-24 13:00:00,33.526889,804.565711,449.250963,68.470501,5.519788,0.000000,97868.316741,1.875000,20.883929,25.957500,8.840333,0.534507
2998,2016-07-24 14:00:00,33.932741,747.396704,449.250963,65.878445,5.390405,0.312178,97885.728963,1.870833,20.876488,26.112750,8.739333,0.536828
2999,2016-07-24 15:00:00,34.335446,635.770837,434.575407,63.384570,5.372491,0.000000,97903.400889,1.866667,20.869048,25.982750,8.631833,0.601656

In [28]:
df.to_csv('../data/mendota_observed.csv', index=False)